server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Logs opcionales para debugging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para login (raíz)
    location = /login {
        proxy_pass http://backend_trainerapp:8080/login;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy al backend
    location /api/ {
	proxy_pass http://backend_trainerapp:8080;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Manejo de CORS opcional
    add_header Access-Control-Allow-Origin *;
}

